export const activityDisplayMap: Record<string, string> = {
  SIGNUP: "Sign Up",
  DAILY_LOGIN: "Daily Login",
  QUIZ_CORRECT: "Quiz Correct",
  ADD_LOG: "Add Log",
  SPOTLIGHT: "Spotlight",
  PROSPERITY_DROP: "Prosperity Drop",
  BUSINESSPROFILE_COMPLETE: "Business Profile Complete",
  MIRACLE_LOG: "Miracle Log",
  PROGRESS_VAULT: "Progress Vault",
  MAGIC_BOX: "Magic Box",
  GENERAL_FEEDBACK: "General Feedback",
  FEATURE_REQUEST: "Feature Request",
  BUG_REPORT: "Bug Report",
};
