export const ROUTE_TITLES: Record<string, string> = {
  dashboard: "Dashboard",
  prosperity: "Prosperity Drops",
  leaderboard: "Leaderboard",
  insights: "Insights",
  subscription: "Subscription",
  miracleLog: "Miracle Log",
  messages: "Messages",
  profile: "Profile",
  faqs: "FAQ's",
  contact: "Contact Us",
  notifications: 'Notifications',
  spotlight: "Spotlight",
  store: "Store",
  'progress-vault': "1% Progress Vault",
};
