export const ROUTE_TITLES: Record<string, string> = {
  dashboard: "Dashboard",
  prosperity: "Prosperity Drops",
  leaderboard: "Leaderboard",
  insights: "Insights",
  subscription: "Subscription",
  "miracle-log": "Miracle Log",
  messages: "Messages",
  profile: "Profile",
  faq: "FAQ's",
  contact: "Contact Us",
  notifications: "Notifications",
  spotlight: "Spotlight",
  store: "Store",
  "progress-vault": "1% Progress Vault",
  "transactions-history": "Transactions",
  "aligned-actions": "1% start",
  // faq: "FAQ",
  "business-profile": "Business Profile",
  "refer-friend": "Refer a Friend",
  "my-profile": "My Profile",
  };
